#!/bin/sh

PROJECT_DIR=$(dirname `readlink -f $0`)/..
# echo ${PROJECT_DIR}

source ${PROJECT_DIR}/env-local.sh; 

cd ${PROJECT_DIR}/back-end/; go test

cd ${PROJECT_DIR}/front-end/; elm-format src/ --validate
