module Config exposing (endPoint)

-- WARNING: this file is automatically generated when
--    running build-payload-config when running locally
--    or building deployable payload

endPoint : String
endPoint =
    "http://0.0.0.0:8002/api/v1"
